Fixing all test make issues. Need to make script to run simulator tests

diff --git a/.github/workflows/verify-build.yml b/.github/workflows/verify-build.yml
--- a/.github/workflows/verify-build.yml
+++ b/.github/workflows/verify-build.yml
@@ -21,3 +21,5 @@ jobs:
       run: make clean
     - name: make stm32f413
       run: make stm32f413
+    - name: make tests
+      run: (for x in Tests/Test_*; do make clean && x="${x%.*}" && make TEST="${x#*_}" || { echo "Error: make command failed"; exit 1; }; done)
